[package]
name = "pfdds-parser"
version = "0.0.0"
description = "TBD"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pfdds-lexer = { path="../pfdds-lexer" }

