[package]
name = "pfdds-lexer"
version = "0.0.0"
description = "TBD"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true


[dependencies]
thiserror.workspace = true

