[package]
name = "rpgle-parser"
version = "0.0.0"
description = "RPGLE Parser"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true

[dev-dependencies]
insta.workspace = true
